backend:
  name: git-gateway
  branch: master

locale: 'ru'

media_folder: static/img
public_folder: /img

collections:
  - name: 'news'
    label: 'Новости'
    folder: 'content/news'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Дата публикации', name: 'date', widget: 'datetime' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }

  - name: 'info'
    label: 'Сведения'
    folder: 'content/info'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Меню', name: 'menu', widget: 'string', default: 'info' }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }
      
  - name: 'students'
    label: 'Ученикам'
    folder: 'content/students'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Меню', name: 'menu', widget: 'string', default: 'students' }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }

  - name: 'parents'
    label: 'Родителям'
    folder: 'content/parents'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Меню', name: 'menu', widget: 'string', default: 'parents' }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }

  - name: 'teachers'
    label: 'Учителям'
    folder: 'content/teachers'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Меню', name: 'menu', widget: 'string', default: 'teachers' }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }

  - name: 'education'
    label: 'Образование'
    folder: 'content/education'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Меню', name: 'menu', widget: 'string', default: 'education' }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }

  - name: 'sidemenu'
    label: 'Боковое меню'
    folder: 'content/sidemenu'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Меню', name: 'menu', widget: 'string', default: 'sidemenu' }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Содержание', name: 'body', widget: 'markdown' }